const ACESSS_CONSTANTS = {
    READ: 'read',
    WRITE: 'write',
    OWNER: 'owner'
};

const SOCKET_EVENTS = {
    JOIN_PROJECT: 'JOIN_PROJECT',
    LEAVE_PROJECT: 'LEAVE_PROJECT',
    UPDATE_PROJECT: 'UPDATE_PROJECT',
    DELETE_PROJECT: 'DELETE_PROJECT',
    ACTIVE_USERS: 'ACTIVE_USERS',
};


module.exports = {
    ACESSS_CONSTANTS,
    SOCKET_EVENTS
};