name: Build and Deploy to Render

on:
  push:
    branches:
      - main  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

    
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/hitendrasinghrathore/hitendrasinghrathore/renkei-backend:latest -f Dockerfile .
          docker push ghcr.io/hitendrasinghrathore/hitendrasinghrathore/renkei-backend:latest
      
      - name: Wait after image push is done
        if: success()
        run: sleep 10

      - name: Deploy to Render backend
        uses: styfle/render-action@v2
        if: success()
        with:
          render_api_token: ${{ secrets.RENDER_API_TOKEN }}
          service_name: renkei-backend
          deployment_description: "Automatic deployment from GitHub Actions"
